name: DumprX-GitLab
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v4

       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/VanVuong41429/Van-DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |
              sudo bash setup.sh
              sudo apt install -y f2fs-tools neofetch
              mkdir -p ~/.ssh
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              # echo "${{ secrets.GIT_TOKEN }}" > .github_token
              # echo "Van-Firmware-Dumps" > .github_orgname
              echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "Van-Firmware-Dumps" > .gitlab_group  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_ed25519  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat
              echo "gitlab.com" > .gitlab_instance
              chmod 600 ~/.ssh/id_ed25519
              wget --no-check-certificate 'https://drive.usercontent.google.com/download?id=1VIPaOLWw_uOViT2VoFidpXNP2-QPAdMN&export=download&authuser=0&confirm=t&uuid=9b04a1dd-b39e-44da-88fd-ab240ed03c08&at=APZUnTVuoVxCMXhYh6cmnRX1HsiR:1711088346755' -O a55x.zip > /dev/null 2>&1 && echo 'Download Complete!'

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
