name: DumprX-GitLab
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v4

       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/VanVuong41429/Van-DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |
              sudo bash setup.sh
              sudo apt install -y f2fs-tools neofetch
              mkdir -p ~/.ssh
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              # echo "${{ secrets.GIT_TOKEN }}" > .github_token
              # echo "Van-Firmware-Dumps" > .github_orgname
              echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "Van-Firmware-Dumps" > .gitlab_group  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_ed25519  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat
              echo "gitlab.com" > .gitlab_instance
              chmod 600 ~/.ssh/id_ed25519

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: DumprX
         run: |
              aria2c -x16 -s8 --console-log-level=warn --summary-interval=0 --check-certificate=false "https://mirrors.lolinet.com/firmware/lenowow/Tab_P11_5G/TB-J607Z/TB-J607Z_S540390_231227_ROW_SVC.7z"
              7z e -y TB-J607Z_S540390_231227_ROW_SVC.7z -o"image" > /dev/null 2>&1 || echo "Extract failed!"
              rm TB-J607Z_S540390_231227_ROW_SVC.7z && cd image
              rm *rawprogram* && mv super_1.img super.img && mv super_2.img odm.img && mv super_3.img product.img && mv super_4.img system.img && mv super_5.img vendor.img
              cd ..
              zip -r image.zip image > /dev/null 2>&1 || echo "Creating failed!"
              rm -rf image
              ./dumper.sh "$ROM_URL"
