name: Dumpyara
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: rokibhasansagar/slimhub_actions@main

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/Van-dumpyara/dumpyara.git

       - name: Setup Dumpyara environment
         working-directory: dumpyara
         run: |
              sudo bash setup.sh
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup config envs
         working-directory: dumpyara
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .githubtoken

       - name: Run the Extra Command
         working-directory: dumpyara
         run: |
              $EXTRA_CMD

       - name: Running Dumpyara
         working-directory: dumpyara
         run: |
              ./dumpyara.sh "$ROM_URL"
